name: adguardhome

services:
  adguardhome:
    image: adguard/adguardhome

    container_name: adguard

    ports:
      - 53:53/tcp
      - 53:53/udp
      - ${PORT}:80/tcp
      - ${ADMIN_PORT}:3000/tcp

    volumes:
      - ${HOMELAB_DATA_DIR}/adguard/conf:/opt/adguardhome/conf
      - ${HOMELAB_DATA_DIR}/adguard/work

    env_file:
      - .env

    restart: unless-stopped

    healthcheck:
      disable: false
