name: adguardhome

services:
  adguardhome:
    image: adguard/adguardhome

    container_name: adguard

    ports:
      - 53:53/tcp
      - 53:53/udp
      - ${ADGUARD_PORT}:80/tcp
      - ${ADGUARD_ADMIN_PORT}:3000/tcp

    volumes:
      - ${HOMELAB_DATA_DIR}/adguard/conf:/opt/adguardhome/conf
      - ${HOMELAB_DATA_DIR}/adguard/work

    environment:
      TZ: ${TZ}

    restart: unless-stopped

    healthcheck:
      disable: false
