name: nginx_proxy_manager

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest

    container_name: nginx_proxy_manager

    ports:
      - 80:80/tcp
      - ${NPM_PORT}:81/tcp
      - 443:443/tcp

    volumes:
      - ${HOMELAB_DATA_DIR}/npm/data:/data
      - ${HOMELAB_DATA_DIR}/npm/letsencrypt:/etc/letsencrypt

    environment:
      TZ: ${TZ}

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:81"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
