name: radarr

services:
  radarr:
    image: ghcr.io/hotio/radarr:latest

    container_name: radarr

    hostname: radarr.internal

    ports:
      - ${RADARR_PORT}:7878

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HOMELAB_DATA_DIR}/radarr:/config
      - ${HOMELAB_DATA_DIR}/Library:/data

    environment:
      PUID: ${HOMELAB_UID}
      PGID: ${HOMELAB_GID}
      TZ: ${TZ}

    restart: unless-stopped

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
