services:
  convertx:
    image: ghcr.io/c4illin/convertx:latest

    container_name: convertx

    ports:
      - ${CONVERTX_PORT}:3000/tcp

    volumes:
      - ${HOMELAB_DATA_DIR}/convertx:/app/data

    environment:
      TZ: ${TZ}
      AUTO_DELETE_EVERY_N_HOURS: ${CONVERTX_AUTO_DELETE_EVERY_N_HOURS}
      HTTP_ALLOWED: ${CONVERTX_HTTP_ALLOWED}
      ALLOW_UNAUTHENTICATED: ${CONVERTX_ALLOW_UNAUTHENTICATED}
      ACCOUNT_REGISTRATION: ${CONVERTX_ACCOUNT_REGISTRATION}
      JWT_SECRET: ${CONVERTX_JWT_SECRET} ## defined in secret/convertx.yaml

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
