name: jellyfin

services:
  jellyfin:
    image: jellyfin/jellyfin:latest

    container_name: jellyfin

    user: "${HOMELAB_UID}:${HOMELAB_GID}"

    ports:
      - ${JELLYFIN_TCP_PORT}:8096/tcp
      - ${JELLYFIN_UDP_PORT}:7359/udp

    volumes:
      - ${HOMELAB_DATA_DIR}/jellyfin/config:/config
      - ${HOMELAB_DATA_DIR}/jellyfin/cache:/cache
      - type: bind
        source: ${HOMELAB_DATA_DIR}/jellyfin/media
        target: /media
      - type: bind
        source: ${HOMELAB_DATA_DIR}/jellyfin/media2
        target: /media2
        read_only: true

    env_file:
        - .env

    environment:
      TZ: ${TZ}

    restart: unless-stopped

    healthcheck:
      disable: false
