name: nextcloud

services:
  db:
    image: mariadb:10.11

    container_name: nextcloud-db

    volumes:
      - ${HOMELAB_DATA_DIR}/nextcloud/db:/var/lib/mysql

    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${NEXTCLOUD_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${NEXTCLOUD_MYSQL_DATABASE}
      MYSQL_USER: ${NEXTCLOUD_MYSQL_USER}
      MYSQL_PASSWORD: ${NEXTCLOUD_MYSQL_PASSWORD}

    restart: unless-stopped

    healthcheck:
      disable: false

  redis:
    image: redis:alpine

    container_name: nextcloud-redis

    restart: unless-stopped

    healthcheck:
      disable: false

  collabora:
    image: collabora/code:latest

    container_name: nextcloud-collabora

    ports:
      - ${COLLABORA_PORT}:9980

    environment:
      TZ: ${TZ}
      aliasgroup1: http://${NEXTCLOUD_TRUSTED_DOMAINS}
      DONT_GEN_SSL_CERT: YES
      extra_params: --o:ssl.enable=false --o:ssl.termination=true

    restart: unless-stopped

    cap_add:
      - MKNOD

  nextcloud:
    image: nextcloud:latest

    container_name: nextcloud

    ports:
      - ${NEXTCLOUD_PORT}:80

    volumes:
      - ${HOMELAB_DATA_DIR}/nextcloud/data:/var/www/html/data
      - ${HOMELAB_DATA_DIR}/nextcloud/html:/var/www/html

    environment:
      TZ: ${TZ}
      MYSQL_HOST: ${NEXTCLOUD_MYSQL_HOST}
      MYSQL_DATABASE: ${NEXTCLOUD_MYSQL_DATABASE}
      MYSQL_USER: ${NEXTCLOUD_MYSQL_USER}
      MYSQL_PASSWORD: ${NEXTCLOUD_MYSQL_PASSWORD}
      REDIS_HOST: ${NEXTCLOUD_REDIS_HOST}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}

    depends_on:
      - db
      - redis

    restart: unless-stopped

    healthcheck:
      disable: false
